database:
  build: ./database
  restart: always
  container_name: ilmo-db
  ports:
    - "8080:8080"
    - "28015:28015"
    - "29015:29015"

server:
  build: ./server
  restart: always
  container_name: ilmo-backend
  links:
    - "database:database"
  ports:
    - "9000:5000"
  volumes:
    - "./server/ilmo:/ilmo"

client:
  build: ./client
  restart: always
  container_name: ilmo-frontend
  ports:
    - "8000:80"
