export default {
  MESSAGES_ADD: 'MESSAGES_ADD',
  MESSAGES_CLEAR: 'MESSAGES_CLEAR',
  MESSAGES_EXPIRE: 'MESSAGES_EXPIRE',
  EVENTS_RECEIVE: 'EVENTS_RECEIVE',
  EVENT_RECEIVE: 'EVENT_RECEIVE',
  CREATE_EVENT_LOADING: 'CREATE_EVENT_LOADING',
  REGISTRATIONS_RECEIVE: 'REGISTRATIONS_RECEIVE',
  CREATE_REGISTRATION_LOADING: 'CREATE_REGISTRATION_LOADING',
};
