export default {
  MESSAGES_ADD: 'MESSAGES_ADD',
  MESSAGES_CLEAR: 'MESSAGES_CLEAR',
  MESSAGES_EXPIRE: 'MESSAGES_EXPIRE',
  EVENTS_RECEIVE: 'EVENTS_RECEIVE',
  EVENT_RECEIVE: 'EVENT_RECEIVE',
  REGISTRATIONS_RECEIVE: 'REGISTRATIONS_RECEIVE',
};
